from web.dom.elements.HTMLUlElement import HTMLUlElement
from web.dom.elements.HTMLH1Element import HTMLH1Element
from web.dom.elements.HTMLBodyElement import HTMLBodyElement
from web.dom.elements.HTMLSlotElement import HTMLSlotElement
from web.dom.elements.HTMLPElement import HTMLPElement
from web.dom.elements.HTMLMenuElement import HTMLMenuElement
from web.dom.elements.HTMLTitleElement import HTMLTitleElement
from web.dom.elements.HTMLTdElement import HTMLTdElement
from web.dom.elements.HTMLEmbedElement import HTMLEmbedElement
from web.dom.elements.HTMLKeygenElement import HTMLKeygenElement
from web.dom.elements.HTMLButtonElement import HTMLButtonElement
from web.dom.elements.HTMLParamElement import HTMLParamElement
from web.dom.elements.HTMLDetailsElement import HTMLDetailsElement
from web.dom.elements.HTMLLabelElement import HTMLLabelElement
from web.dom.elements.HTMLDirElement import HTMLDirElement
from web.dom.elements.HTMLColgroupElement import HTMLColgroupElement
from web.dom.elements.HTMLScriptElement import HTMLScriptElement
from web.dom.elements.HTMLSupElement import HTMLSupElement
from web.dom.elements.HTMLTableElement import HTMLTableElement
from web.dom.elements.HTMLBrElement import HTMLBrElement
from web.dom.elements.HTMLRbElement import HTMLRbElement
from web.dom.elements.HTMLBasefontElement import HTMLBasefontElement
from web.dom.elements.HTMLEmElement import HTMLEmElement
from web.dom.elements.HTMLVideoElement import HTMLVideoElement
from web.dom.elements.HTMLAElement import HTMLAElement
from web.dom.elements.HTMLUElement import HTMLUElement
from web.dom.elements.HTMLBdoElement import HTMLBdoElement
from web.dom.elements.HTMLDatalistElement import HTMLDatalistElement
from web.dom.elements.HTMLTimeElement import HTMLTimeElement
from web.dom.elements.HTMLAddressElement import HTMLAddressElement
from web.dom.elements.HTMLAcronymElement import HTMLAcronymElement
from web.dom.elements.HTMLThElement import HTMLThElement
from web.dom.elements.HTMLWbrElement import HTMLWbrElement
from web.dom.elements.HTMLLiElement import HTMLLiElement
from web.dom.elements.HTMLTemplateElement import HTMLTemplateElement
from web.dom.elements.HTMLMainElement import HTMLMainElement
from web.dom.elements.HTMLFieldsetElement import HTMLFieldsetElement
from web.dom.elements.HTMLStrikeElement import HTMLStrikeElement
from web.dom.elements.HTMLCenterElement import HTMLCenterElement
from web.dom.elements.HTMLMetaElement import HTMLMetaElement
from web.dom.elements.HTMLKbdElement import HTMLKbdElement
from web.dom.elements.HTMLMarkElement import HTMLMarkElement
from web.dom.elements.HTMLFontElement import HTMLFontElement
from web.dom.elements.HTMLBaseElement import HTMLBaseElement
from web.dom.elements.HTMLTfootElement import HTMLTfootElement
from web.dom.elements.HTMLDialogElement import HTMLDialogElement
from web.dom.elements.HTMLAbbrElement import HTMLAbbrElement
from web.dom.elements.HTMLDtElement import HTMLDtElement
from web.dom.elements.HTMLTrackElement import HTMLTrackElement
from web.dom.elements.HTMLFigcaptionElement import HTMLFigcaptionElement
from web.dom.elements.HTMLNavElement import HTMLNavElement
from web.dom.elements.HTMLFooterElement import HTMLFooterElement
from web.dom.elements.HTMLQElement import HTMLQElement
from web.dom.elements.HTMLLegendElement import HTMLLegendElement
from web.dom.elements.HTMLDdElement import HTMLDdElement
from web.dom.elements.HTMLTtElement import HTMLTtElement
from web.dom.elements.HTMLMarqueeElement import HTMLMarqueeElement
from web.dom.elements.HTMLVarElement import HTMLVarElement
from web.dom.elements.HTMLIElement import HTMLIElement
from web.dom.elements.HTMLNobrElement import HTMLNobrElement
from web.dom.elements.HTMLBlockquoteElement import HTMLBlockquoteElement
from web.dom.elements.HTMLH3Element import HTMLH3Element
from web.dom.elements.HTMLSmallElement import HTMLSmallElement
from web.dom.elements.HTMLElement import HTMLElement
from web.dom.elements.HTMLImgElement import HTMLImgElement
from web.dom.elements.HTMLAsideElement import HTMLAsideElement
from web.dom.elements.HTMLInputElement import HTMLInputElement
from web.dom.elements.HTMLNoscriptElement import HTMLNoscriptElement
from web.dom.elements.HTMLFigureElement import HTMLFigureElement
from web.dom.elements.HTMLOlElement import HTMLOlElement
from web.dom.elements.HTMLH2Element import HTMLH2Element
from web.dom.elements.HTMLCaptionElement import HTMLCaptionElement
from web.dom.elements.HTMLArticleElement import HTMLArticleElement
from web.dom.elements.HTMLSvgElement import HTMLSvgElement
from web.dom.elements.HTMLObjectElement import HTMLObjectElement
from web.dom.elements.HTMLAppletElement import HTMLAppletElement
from web.dom.elements.HTMLMathElement import HTMLMathElement
from web.dom.elements.HTMLPreElement import HTMLPreElement
from web.dom.elements.HTMLTextareaElement import HTMLTextareaElement
from web.dom.elements.HTMLH6Element import HTMLH6Element
from web.dom.elements.HTMLIframeElement import HTMLIframeElement
from web.dom.elements.HTMLSourceElement import HTMLSourceElement
from web.dom.elements.HTMLCodeElement import HTMLCodeElement
from web.dom.elements.HTMLSubElement import HTMLSubElement
from web.dom.elements.HTMLSelectElement import HTMLSelectElement
from web.dom.elements.HTMLMeterElement import HTMLMeterElement
from web.dom.elements.HTMLSElement import HTMLSElement
from web.dom.elements.HTMLHeadElement import HTMLHeadElement
from web.dom.elements.HTMLInsElement import HTMLInsElement
from web.dom.elements.HTMLHeaderElement import HTMLHeaderElement
from web.dom.elements.HTMLHrElement import HTMLHrElement
from web.dom.elements.HTMLAudioElement import HTMLAudioElement
from web.dom.elements.HTMLHgroupElement import HTMLHgroupElement
from web.dom.elements.HTMLImageElement import HTMLImageElement
from web.dom.elements.HTMLPictureElement import HTMLPictureElement
from web.dom.elements.HTMLFormElement import HTMLFormElement
from web.dom.elements.HTMLBElement import HTMLBElement
from web.dom.elements.HTMLTbodyElement import HTMLTbodyElement
from web.dom.elements.HTMLStrongElement import HTMLStrongElement
from web.dom.elements.HTMLProgressElement import HTMLProgressElement
from web.dom.elements.HTMLRubyElement import HTMLRubyElement
from web.dom.elements.HTMLRtcElement import HTMLRtcElement
from web.dom.elements.HTMLFrameElement import HTMLFrameElement
from web.dom.elements.HTMLCiteElement import HTMLCiteElement
from web.dom.elements.HTMLDataElement import HTMLDataElement
from web.dom.elements.HTMLDlElement import HTMLDlElement
from web.dom.elements.HTMLDivElement import HTMLDivElement
from web.dom.elements.HTMLBlinkElement import HTMLBlinkElement
from web.dom.elements.HTMLMapElement import HTMLMapElement
from web.dom.elements.HTMLSampElement import HTMLSampElement
from web.dom.elements.Text import Text
from web.dom.elements.HTMLOptionElement import HTMLOptionElement
from web.dom.elements.HTMLNoembedElement import HTMLNoembedElement
from web.dom.elements.HTMLRpElement import HTMLRpElement
from web.dom.elements.HTMLPathElement import HTMLPathElement
from web.dom.elements.HTMLBigElement import HTMLBigElement
from web.dom.elements.HTMLAreaElement import HTMLAreaElement
from web.dom.elements.HTMLListingElement import HTMLListingElement
from web.dom.elements.HTMLBgsoundElement import HTMLBgsoundElement
from web.dom.elements.HTMLH5Element import HTMLH5Element
from web.dom.elements.HTMLColElement import HTMLColElement
from web.dom.elements.HTMLSummaryElement import HTMLSummaryElement
from web.dom.elements.Comment import Comment
from web.dom.elements.HTMLTrElement import HTMLTrElement
from web.dom.elements.HTMLPlaintextElement import HTMLPlaintextElement
from web.dom.elements.HTMLFramesetElement import HTMLFramesetElement
from web.dom.elements.HTMLDelElement import HTMLDelElement
from web.dom.elements.HTMLRtElement import HTMLRtElement
from web.dom.elements.HTMLNoframesElement import HTMLNoframesElement
from web.dom.elements.HTMLSectionElement import HTMLSectionElement
from web.dom.elements.HTMLBdiElement import HTMLBdiElement
from web.dom.elements.HTMLCanvasElement import HTMLCanvasElement
from web.dom.elements.HTMLTheadElement import HTMLTheadElement
from web.dom.elements.HTMLOutputElement import HTMLOutputElement
from web.dom.elements.HTMLDfnElement import HTMLDfnElement
from web.dom.elements.HTMLStyleElement import HTMLStyleElement
from web.dom.elements.HTMLH4Element import HTMLH4Element
from web.dom.elements.HTMLLinkElement import HTMLLinkElement
from web.dom.elements.HTMLOptgroupElement import HTMLOptgroupElement
from web.dom.elements.HTMLXmpElement import HTMLXmpElement
from web.dom.elements.HTMLSpanElement import HTMLSpanElement
