import web.dom.elements.HTMLUlElement as HTMLUlElement
import web.dom.elements.HTMLH1Element as HTMLH1Element
import web.dom.elements.HTMLBodyElement as HTMLBodyElement
import web.dom.elements.HTMLSlotElement as HTMLSlotElement
import web.dom.elements.HTMLPElement as HTMLPElement
import web.dom.elements.HTMLMenuElement as HTMLMenuElement
import web.dom.elements.HTMLTitleElement as HTMLTitleElement
import web.dom.elements.HTMLTdElement as HTMLTdElement
import web.dom.elements.HTMLEmbedElement as HTMLEmbedElement
import web.dom.elements.HTMLKeygenElement as HTMLKeygenElement
import web.dom.elements.HTMLButtonElement as HTMLButtonElement
import web.dom.elements.HTMLParamElement as HTMLParamElement
import web.dom.elements.HTMLDetailsElement as HTMLDetailsElement
import web.dom.elements.HTMLLabelElement as HTMLLabelElement
import web.dom.elements.HTMLDirElement as HTMLDirElement
import web.dom.elements.HTMLColgroupElement as HTMLColgroupElement
import web.dom.elements.HTMLScriptElement as HTMLScriptElement
import web.dom.elements.HTMLSupElement as HTMLSupElement
import web.dom.elements.HTMLTableElement as HTMLTableElement
import web.dom.elements.HTMLBrElement as HTMLBrElement
import web.dom.elements.HTMLRbElement as HTMLRbElement
import web.dom.elements.HTMLBasefontElement as HTMLBasefontElement
import web.dom.elements.HTMLEmElement as HTMLEmElement
import web.dom.elements.HTMLVideoElement as HTMLVideoElement
import web.dom.elements.HTMLAElement as HTMLAElement
import web.dom.elements.HTMLUElement as HTMLUElement
import web.dom.elements.HTMLBdoElement as HTMLBdoElement
import web.dom.elements.HTMLDatalistElement as HTMLDatalistElement
import web.dom.elements.HTMLTimeElement as HTMLTimeElement
import web.dom.elements.HTMLAddressElement as HTMLAddressElement
import web.dom.elements.HTMLAcronymElement as HTMLAcronymElement
import web.dom.elements.HTMLThElement as HTMLThElement
import web.dom.elements.HTMLWbrElement as HTMLWbrElement
import web.dom.elements.HTMLLiElement as HTMLLiElement
import web.dom.elements.HTMLTemplateElement as HTMLTemplateElement
import web.dom.elements.HTMLMainElement as HTMLMainElement
import web.dom.elements.HTMLFieldsetElement as HTMLFieldsetElement
import web.dom.elements.HTMLStrikeElement as HTMLStrikeElement
import web.dom.elements.HTMLCenterElement as HTMLCenterElement
import web.dom.elements.HTMLMetaElement as HTMLMetaElement
import web.dom.elements.HTMLKbdElement as HTMLKbdElement
import web.dom.elements.HTMLMarkElement as HTMLMarkElement
import web.dom.elements.HTMLFontElement as HTMLFontElement
import web.dom.elements.HTMLBaseElement as HTMLBaseElement
import web.dom.elements.HTMLTfootElement as HTMLTfootElement
import web.dom.elements.HTMLDialogElement as HTMLDialogElement
import web.dom.elements.HTMLAbbrElement as HTMLAbbrElement
import web.dom.elements.HTMLDtElement as HTMLDtElement
import web.dom.elements.HTMLTrackElement as HTMLTrackElement
import web.dom.elements.HTMLFigcaptionElement as HTMLFigcaptionElement
import web.dom.elements.HTMLNavElement as HTMLNavElement
import web.dom.elements.HTMLFooterElement as HTMLFooterElement
import web.dom.elements.HTMLQElement as HTMLQElement
import web.dom.elements.HTMLLegendElement as HTMLLegendElement
import web.dom.elements.HTMLDdElement as HTMLDdElement
import web.dom.elements.HTMLTtElement as HTMLTtElement
import web.dom.elements.HTMLMarqueeElement as HTMLMarqueeElement
import web.dom.elements.HTMLVarElement as HTMLVarElement
import web.dom.elements.HTMLIElement as HTMLIElement
import web.dom.elements.HTMLNobrElement as HTMLNobrElement
import web.dom.elements.HTMLBlockquoteElement as HTMLBlockquoteElement
import web.dom.elements.HTMLH3Element as HTMLH3Element
import web.dom.elements.HTMLSmallElement as HTMLSmallElement
import web.dom.elements.HTMLElement as HTMLElement
import web.dom.elements.HTMLImgElement as HTMLImgElement
import web.dom.elements.HTMLAsideElement as HTMLAsideElement
import web.dom.elements.HTMLInputElement as HTMLInputElement
import web.dom.elements.HTMLNoscriptElement as HTMLNoscriptElement
import web.dom.elements.HTMLFigureElement as HTMLFigureElement
import web.dom.elements.HTMLOlElement as HTMLOlElement
import web.dom.elements.HTMLH2Element as HTMLH2Element
import web.dom.elements.HTMLCaptionElement as HTMLCaptionElement
import web.dom.elements.HTMLArticleElement as HTMLArticleElement
import web.dom.elements.HTMLSvgElement as HTMLSvgElement
import web.dom.elements.HTMLObjectElement as HTMLObjectElement
import web.dom.elements.HTMLAppletElement as HTMLAppletElement
import web.dom.elements.HTMLMathElement as HTMLMathElement
import web.dom.elements.Element as Element
import web.dom.elements.HTMLPreElement as HTMLPreElement
import web.dom.elements.HTMLTextareaElement as HTMLTextareaElement
import web.dom.elements.HTMLH6Element as HTMLH6Element
import web.dom.elements.HTMLIframeElement as HTMLIframeElement
import web.dom.elements.HTMLSourceElement as HTMLSourceElement
import web.dom.elements.HTMLCodeElement as HTMLCodeElement
import web.dom.elements.HTMLSubElement as HTMLSubElement
import web.dom.elements.HTMLSelectElement as HTMLSelectElement
import web.dom.elements.HTMLMeterElement as HTMLMeterElement
import web.dom.elements.HTMLSElement as HTMLSElement
import web.dom.elements.HTMLHeadElement as HTMLHeadElement
import web.dom.elements.HTMLInsElement as HTMLInsElement
import web.dom.elements.HTMLHeaderElement as HTMLHeaderElement
import web.dom.elements.HTMLHrElement as HTMLHrElement
import web.dom.elements.HTMLAudioElement as HTMLAudioElement
import web.dom.elements.HTMLHgroupElement as HTMLHgroupElement
import web.dom.elements.HTMLImageElement as HTMLImageElement
import web.dom.elements.HTMLPictureElement as HTMLPictureElement
import web.dom.elements.HTMLFormElement as HTMLFormElement
import web.dom.elements.HTMLBElement as HTMLBElement
import web.dom.elements.HTMLTbodyElement as HTMLTbodyElement
import web.dom.elements.HTMLStrongElement as HTMLStrongElement
import web.dom.elements.HTMLProgressElement as HTMLProgressElement
import web.dom.elements.HTMLRubyElement as HTMLRubyElement
import web.dom.elements.HTMLRtcElement as HTMLRtcElement
import web.dom.elements.HTMLFrameElement as HTMLFrameElement
import web.dom.elements.HTMLCiteElement as HTMLCiteElement
import web.dom.elements.HTMLDataElement as HTMLDataElement
import web.dom.elements.HTMLDlElement as HTMLDlElement
import web.dom.elements.HTMLDivElement as HTMLDivElement
import web.dom.elements.HTMLBlinkElement as HTMLBlinkElement
import web.dom.elements.HTMLMapElement as HTMLMapElement
import web.dom.elements.HTMLSampElement as HTMLSampElement
import web.dom.elements.Text as Text
import web.dom.elements.HTMLOptionElement as HTMLOptionElement
import web.dom.elements.HTMLNoembedElement as HTMLNoembedElement
import web.dom.elements.HTMLRpElement as HTMLRpElement
import web.dom.elements.HTMLPathElement as HTMLPathElement
import web.dom.elements.HTMLBigElement as HTMLBigElement
import web.dom.elements.HTMLAreaElement as HTMLAreaElement
import web.dom.elements.HTMLListingElement as HTMLListingElement
import web.dom.elements.HTMLBgsoundElement as HTMLBgsoundElement
import web.dom.elements.HTMLH5Element as HTMLH5Element
import web.dom.elements.HTMLColElement as HTMLColElement
import web.dom.elements.HTMLSummaryElement as HTMLSummaryElement
import web.dom.elements.Comment as Comment
import web.dom.elements.HTMLTrElement as HTMLTrElement
import web.dom.elements.HTMLPlaintextElement as HTMLPlaintextElement
import web.dom.elements.HTMLFramesetElement as HTMLFramesetElement
import web.dom.elements.HTMLDelElement as HTMLDelElement
import web.dom.elements.HTMLRtElement as HTMLRtElement
import web.dom.elements.HTMLNoframesElement as HTMLNoframesElement
import web.dom.elements.HTMLSectionElement as HTMLSectionElement
import web.dom.elements.HTMLBdiElement as HTMLBdiElement
import web.dom.elements.HTMLCanvasElement as HTMLCanvasElement
import web.dom.elements.HTMLTheadElement as HTMLTheadElement
import web.dom.elements.HTMLOutputElement as HTMLOutputElement
import web.dom.elements.HTMLDfnElement as HTMLDfnElement
import web.dom.elements.HTMLStyleElement as HTMLStyleElement
import web.dom.elements.HTMLH4Element as HTMLH4Element
import web.dom.elements.HTMLLinkElement as HTMLLinkElement
import web.dom.elements.HTMLOptgroupElement as HTMLOptgroupElement
import web.dom.elements.HTMLXmpElement as HTMLXmpElement
import web.dom.elements.HTMLSpanElement as HTMLSpanElement
