import unittest

from web.css.CSSTokenizer import CSSTokenizer, convert_to_number, is_non_printable
from web.css.CSSToken import TokenType, EOFToken


class TestCSSTokenizer(unittest.TestCase):

    def test_preprocessing(self):
        # Define a set of test cases with inputs and expected outputs
        test_cases = [
            # CR (U+000D) should become LF
            ('\r', '\n'),
            # FF (U+000C) should become LF
            ('\f', '\n'),
            # NULL (U+0000) should become U+FFFD replacement character
            ('\u0000', '\uFFFD'),
            # Surrogate code points should become U+FFFD
            ('\uD800', '\uFFFD'),
            ('\uDBFF', '\uFFFD'),
            ('\uDFFF', '\uFFFD'),
            # Normal characters should remain unchanged
            ('A', 'A'),
            ('\n', '\n'),  # LF should remain LF
            ('😊', '😊'),  # Emoji character remains unchanged
        ]

        # Test each case using subTest to isolate each input-output pair
        for char, expected in test_cases:
            with self.subTest(char=char):
                self.assertEqual(CSSTokenizer.preprocess_code_point(char), expected)


    def test_consume_comment(self):
        css_string = "/* This is a css comment. */"
        tokenizer = CSSTokenizer(css_string)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.EOF)

    def test_consume_comment_with_style(self):
        css_string = "/* This is a css comment. */ * { margin: 0px; }"
        tokenizer = CSSTokenizer(css_string)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.WHITESPACE)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DELIM)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.WHITESPACE)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.LCURLY)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.WHITESPACE)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DELIM)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DELIM)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DELIM)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DELIM)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DELIM)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DELIM)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.COLON)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.WHITESPACE)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.DIMENSION)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.WHITESPACE)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.RCURLY)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.EOF)


    def test_consume_whitespace(self):
        css_string = """   
        
        """
        tokenizer = CSSTokenizer(css_string)
        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.WHITESPACE)

        token = tokenizer.next_token()
        self.assertEqual(token.token_type, TokenType.EOF)

    def test_consume_escaped_code_point(self):
        css_string = "Hello\\41 World"
        tokenizer = CSSTokenizer(css_string)
        tokenizer.current_cursor_position = 5
        char = tokenizer.consume_escaped_code_point()
        self.assertEqual(char, "A")

    def test_convert_to_number(self):
        self.assertEqual(convert_to_number("123.456e2"), 12345.6)
        self.assertEqual(convert_to_number("-1.23e-4"), -0.000123)
        self.assertEqual(convert_to_number("42"), 42)
        self.assertEqual(convert_to_number("3.14"), 3.14)
        self.assertEqual(convert_to_number("100e+2"), 10000)

    def test_is_non_printable(self):
        self.assertEqual(is_non_printable("\x00"), True)
        self.assertEqual(is_non_printable("\x08"), True)
        self.assertEqual(is_non_printable("\x0B"), True)
        self.assertEqual(is_non_printable("\x1F"), True)
        self.assertEqual(is_non_printable("\x7F"), True)
        self.assertEqual(is_non_printable("A"), False)

    def test_css_tokenizer(self):
        css_string = """
        /* Global Styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background-color: #f4f4f9;
  color: #333;
}

/* Basic Selectors and Properties */
h1 {
  font-size: 2em;
  color: #007acc;
}

p {
  line-height: 1.6;
}

a {
  color: #007acc;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* Class and ID Selectors */
.container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

#header {
  text-align: center;
  padding: 10px;
  background-color: #007acc;
  color: #fff;
}

/* Attribute Selectors */
input[type="text"] {
  padding: 10px;
  border: 1px solid #ccc;
}

/* Pseudo-classes */
button:hover {
  background-color: #007acc;
  color: #fff;
}

button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

/* Pseudo-elements */
p::first-line {
  font-weight: bold;
}

blockquote::before {
  content: "“";
  font-size: 2em;
  color: #999;
}

blockquote::after {
  content: "”";
  font-size: 2em;
  color: #999;
}

/* Child and Sibling Combinators */
ul li:first-child {
  font-weight: bold;
}

ul li + li {
  margin-top: 5px;
}

/* Media Queries */
@media (max-width: 600px) {
  body {
    font-size: 0.9em;
  }

  .container {
    padding: 10px;
  }
}

/* Keyframe Animations */
@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.fade-in {
  animation: fadeIn 2s ease-in-out;
}

/* CSS Grid */
.grid-container {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

.grid-item {
  background-color: #007acc;
  color: white;
  padding: 20px;
  text-align: center;
}

/* Flexbox */
.flex-container {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.flex-item {
  background-color: #e0e0e0;
  padding: 10px;
}

/* CSS Variables */
:root {
  --primary-color: #007acc;
  --secondary-color: #333;
  --font-size-large: 1.5em;
}

.header {
  background-color: var(--primary-color);
  color: #fff;
  font-size: var(--font-size-large);
}

/* Complex Selectors */
ul > li:nth-child(odd) {
  background-color: #f4f4f4;
}

ul li:nth-child(3n) {
  color: var(--secondary-color);
}

/* Transformations and Transitions */
.button {
  padding: 10px 20px;
  background-color: var(--primary-color);
  color: #fff;
  border: none;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.button:hover {
  background-color: #005f99;
}

.button:active {
  transform: scale(0.98);
}

/* Grid Area Naming */
.grid-layout {
  display: grid;
  grid-template-areas: 
    "header header"
    "sidebar main"
    "footer footer";
}

.header { grid-area: header; }
.sidebar { grid-area: sidebar; }
.main { grid-area: main; }
.footer { grid-area: footer; }

/* CSS Counters */
ol.counter {
  counter-reset: list-counter;
}

ol.counter li {
  counter-increment: list-counter;
}

ol.counter li::before {
  content: counter(list-counter) ". ";
  font-weight: bold;
}
        """
        expected_tokens = [TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COMMA,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.NUMBER,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.NUMBER,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LBRACKET,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.STRING,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.STRING,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.STRING,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LPAREN,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LPAREN,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LPAREN,
                  TokenType.IDENT,
                  TokenType.RPAREN,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LPAREN,
                  TokenType.IDENT,
                  TokenType.RPAREN,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.LPAREN,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.RPAREN,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.NUMBER,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.LPAREN,
                  TokenType.DIMENSION,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LPAREN,
                  TokenType.IDENT,
                  TokenType.RPAREN,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.DIMENSION,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LPAREN,
                  TokenType.IDENT,
                  TokenType.RPAREN,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.DIMENSION,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DIMENSION,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LPAREN,
                  TokenType.NUMBER,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.STRING,
                  TokenType.WHITESPACE,
                  TokenType.STRING,
                  TokenType.WHITESPACE,
                  TokenType.STRING,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.COLON,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.WHITESPACE,
                  TokenType.LCURLY,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.LPAREN,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.RPAREN,
                  TokenType.WHITESPACE,
                  TokenType.STRING,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.IDENT,
                  TokenType.COLON,
                  TokenType.WHITESPACE,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.DELIM,
                  TokenType.SEMICOLON,
                  TokenType.WHITESPACE,
                  TokenType.RCURLY,
                  TokenType.WHITESPACE,
                  TokenType.EOF]
        tokenizer = CSSTokenizer(css_string)
        for expected_token in expected_tokens:
            token = tokenizer.next_token()
            with self.subTest(char=token):
                self.assertEqual(expected_token, token.token_type)